### ISSUE TITLE
反鞘翅导弹井敌我判定设置失效

### ISSUE THREAD

**Issue by outlookhude** [SlimefunGuguProject/MissileWarfare#31]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/MissileWarfare/issues)，且没有找到相同的问题

### 问题描述

在1.20.2，paper服务端中，在使用**敌我识别系统配置器**右键**反鞘翅导弹井**时没有任何反应且服务端**会出现一次报错**，使用**木棍**右键则会**直接打开容器界面**

### 复现步骤

在使用**敌我识别系统配置器**右键**反鞘翅导弹井**时没有任何反应且服务端**会出现一次报错**，使用**木棍**右键则会**直接打开容器界面**

### 预期行为

在使用**敌我识别系统配置器/木棍**右键**反鞘翅导弹发射井**时应能正常设置白名单

### 服务器日志

[09:41:41 ERROR]: [MissileWarfare] Item "ANTIELYTRA" from MissileWarfare vBuild 15 (git 56f41bc) has caused an Error!
[09:41:41 ERROR]: [MissileWarfare] Could not pass "BlockUseHandler" for AntiElytraLauncher - 'ANTIELYTRA' (MissileWarfare vBuild 15 (git 56f41bc))
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R2.block.impl.CraftDispenser cannot be cast to class org.bukkit.block.TileState (org.bukkit.craftbukkit.v1_20_R2.block.impl.CraftDispenser and org.bukkit.block.TileState are in unnamed module of loader java.net.URLClassLoader @3eb07fd3)
        at me.kaiyan.missilewarfare.blocks.AntiElytraLauncher.onBlockRightClick(AntiElytraLauncher.java:147) ~[MissileWarfare-Build 15 (git 56f41bc).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.lambda$rightClickBlock$1(SlimefunItemInteractListener.java:118) ~[Slimefun-eabaa21-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:1003) ~[Slimefun-eabaa21-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickBlock(SlimefunItemInteractListener.java:118) ~[Slimefun-eabaa21-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:68) ~[Slimefun-eabaa21-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-279]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-279]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-279]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1907) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 服务端软件

Paper

### Minecraft 版本

1.20.2

### Slimefun版本

Slimefun eabaa21-beta
paper git-paper-279
java 17
missilewarfare vbuild 15(git 56f41bc)

### 插件版本

vbuild 15(git 56f41bc)

**Comment by Gao12354** [comment]
同上

**Comment by ybw0014** [comment]
重新从上游拉了新版本，请尝试使用最新构建

**Comment by outlookhude** [comment]
> 重新从上游拉了新版本，请尝试使用最新构建

然而好消息是，构建16除了使得颜色代码失效和部分提示语不显示以外，没有任何进展……
